management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ 'health','env','info' ]
spring:
  application:
    name: provider
  profiles:
    active: first
  security:
    user:
      name: root
      password: root
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://localhost:7777