server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://erk2.com:7002/eureka
    healthcheck:
      # 是否设置健康检查
      enabled: true
  instance:
    hostname: eureka-provider
    instance-id: provider-ins-1
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ['health','env','info']
info:
  app:
    name: eureka-provider
    version: 1.0.0
    description: 测试
spring:
  application:
    name: provider
ribbon:
  eureka:
    enabled: true