#
#eureka:
#  client:
#    # 是否将自己注册到Eureka服务注册中心上
#    register-with-eureka: false
#    # 是否从Eureka上拉取服务注册信息
#    fetch-registry: false
#    serviceUrl:
#     defaultZone: http://127.0.0.1:8080/eureka
#  server:
#    enable-self-preservation: false
#spring:
#  application:
#    name: eureka-server
#server:
    #  port: 8762

spring:
  profiles:
    active: erk2
  application:
    name: EurekaServer
eureka:
  server:
    # 是否开启自我保护模式
    enable-self-preservation: true
    # 失效服务器间隔
    eviction-interval-timer-in-ms: 3000