eureka:
  client:
    service-url:
#      defaultZone: http://erk1.com:7001/eureka
      defaultZone: http://erk2.com:7002/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: erk2.com
  # 自定义标签
  metadata-map:
      creater: chenzifeng
server:
  port: 7002
