server:
  port: 8081
  servlet: /userManager
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_program?tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8r&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource

  # 当前激活的配置文件是：
  profiles:
    active: dev
    # mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true

