eureka:
  client:
    serviceUrl:
      # 服务中心地址
      defaultZone: http://erk2.com:7002/eureka
    # eureka client 拉取服务注册信息的时间间隔，默认30s
    # 对于api-gateway，如果需要迅速获取服务注册状态，可以减小该值
    registry-fetch-interval-seconds: 25
  instance:
    # 续约（心跳）发送间隔时间，默认30s
    lease-renewal-interval-in-seconds: 25
    # 续约到期时间，默认90s
    lease-expiration-duration-in-seconds: 60
spring:
  application:
    name: chenzifeng-spring-cloud-eureka-client-1
server:
  port: 8081