spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_manage
    username: root
    password: czf001413
    test-while-idle: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver