spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  application:
    name: book_manage
#  datasource:
#    url: localhost:3306
#    username: root
#    password: czf001413
#    driver-class-name: com.
server:
  port: 8081