server:
  port: 9111
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
  security:
    user:
      name: admin
      password: 123456
  session:
    store-type: redis
    timeout: PT30M # 30∑÷÷”
