#spring:
#  #  security:
#  #    user:
#  #      name: root
#  #      password: root
#  application:
#    name: consumer
#  boot:
#    admin:
#      client:
#        url: http://localhost:7777
#
#  profiles:
#    active: dev
#
#feign:
#  # 开启hystrix
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connncetTime: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#info:
#  app:
#    name: eureka-consumer
#    version: 1.0.0
#    description: 测试
server:
  port: 8092
